version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ics-delivery-db
    restart: always
    environment:
      POSTGRES_USER: delivery_user
      POSTGRES_PASSWORD: delivery_password
      POSTGRES_DB: delivery_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
